### ISSUE TITLE
error 07 when requesting https: site in xb

### ISSUE THREAD

**Issue by arcadeshopper** [jedimatt42/tipi#114]
2019-11-12 16:24:35,420 Pab         : INFO     opcode: Open, fileType: Sequential, mode: Input, dataType: Display, recordType: Variable, recordLength: 128, recordNumber: 0
2019-11-12 16:24:35,421 CurlFile    : INFO     open devname - PI.https://tgftp.nws.noaa.gov/data/observations/metar/decoded/KPDX.TXT
2019-11-12 16:24:35,422 CurlFile    : INFO     url: https://tgftp.nws.noaa.gov/data/observations/metar/decoded/KPDX.TXT
2019-11-12 16:24:35,423 CurlFile    : INFO     cmd: wget -O /tmp/CF https://tgftp.nws.noaa.gov/data/observations/metar/decoded/KPDX.TXT
2019-11-12 16:24:35,946 ti_files.NativeFile: ERROR    not a valid NativeFile /tmp/CF
Traceback (most recent call last):
  File "/home/tipi/tipi/services/ti_files/NativeFile.py", line 32, in load
    raise Exception("Incompatible recordlength")
Exception: Incompatible recordlength
2019-11-12 16:24:35,947 CurlFile    : ERROR    failed
Traceback (most recent call last):
  File "/home/tipi/tipi/services/CurlFile.py", line 60, in open
    file = self.fetch(url, pab)
  File "/home/tipi/tipi/services/CurlFile.py", line 174, in fetch
    return NativeFile.load(tmpname, pab, url)
  File "/home/tipi/tipi/services/ti_files/NativeFile.py", line 32, in load
    raise Exception("Incompatible recordlength")
Exception: Incompatible recordlength

xbcode opens file as input, variable 254 also tried 128

**Comment by jedimatt42** [comment]
10 OPEN #1:"PI.HTTPS://tgftp.nws.noaa.gov/data/observations/metar/decoded/KPDX.TXT",INPUT, VARIABLE 254
20 LINPUT #1:A$
30 PRINT A$
40 GOTO 20

The above works... 

also no record length works, giving 80... and tested 10, which just cuts lines short per a separate issue that is filed...
