### ISSUE TITLE
safepoint in middle of request handling?

### ISSUE THREAD

**Issue by jedimatt42** [jedimatt42/tipi#122]
2020-05-17 15:13:34,483 Pab         : INFO     opcode: Close, fileType: Relative, mode: Input, dataType: Internal, recordType: Fixed, recordLength: 38, recordNumber: 74
2020-05-17 15:13:34,483 TipiDisk    : ERROR    responding with error: 0
Traceback (most recent call last):
  File "./TipiService.py", line 51, in <module>
    msg = tipi_io.receive()
  File "/home/tipi/tipi/services/tipi/TipiMessage.py", line 129, in receive
    self.__resetProtocol()
  File "/home/tipi/tipi/services/tipi/TipiMessage.py", line 83, in __resetProtocol
    raise BackOffException('safepoint')
BackOffException: safepoint
2020-05-17 15:13:34,484 TipiService : INFO     Request completed.

**Comment by jedimatt42** [comment]
I made several attempts to fix, and then PeteE rewrote some of this logic when it moved into the native code... seems fixed.
