### ISSUE TITLE
status on PI.STATUS file

### ISSUE THREAD

**Issue by jedimatt42** [jedimatt42/tipi#143]
status opcode support is spotty on PI. device pseudo files.

2020-12-19 13:37:13,546 TipiService : ERROR    Unhandled exception in main
Traceback (most recent call last):
  File "./TipiService.py", line 79, in <module>
    if specialFiles.handle(pab, filename):
  File "/home/tipi/tipi/services/SpecialFiles.py", line 50, in handle
    handler.handle(pab, devname)
  File "/home/tipi/tipi/services/StatusFile.py", line 34, in handle
    self.status(pab, devname)
  File "/home/tipi/tipi/services/StatusFile.py", line 79, in status
    if readRec >= self.tipiStatus.len():
AttributeError: 'list' object has no attribute 'len'

**Comment by jedimatt42** [comment]
this turned out to be a bug caused by my python2 code getting missed in python3 conversion.
