### ISSUE TITLE
socket error

### ISSUE THREAD

**Issue by arcadeshopper** [jedimatt42/tipi#152]
while on my afterhours bbs i got disconnected and this is in the log

2021-09-07 21:50:31,216 TipiService : ERROR    Unhandled exception in main
Traceback (most recent call last):
  File "./TipiService.py", line 65, in <module>
    if levelTwo.handle(msg):
  File "/home/tipi/tipi/services/LevelTwo.py", line 37, in handle
    handler = self.handlers.get(msg[0], self.defaultHandler)
IndexError: bytearray index out of range
2021-09-07 21:50:31,653 TipiService : INFO     physical mode enabled
2021-09-07 21:50:31,654 TipiService : INFO     TIPI Ready

**Comment by jedimatt42** [comment]
That looks like a random transmission error or programmer error on the client side.  The client is requesting a LVL2 disk io routine that is unsupported by the TIPI.

This could only happen if a client is bi-passing the DSR and messaging to the TIPI LVL2 disk directly. Since no one but myself is knowledgeable enough to do that, it is most likely that the cable between the TIPI board and the Raspberry PI caused a glitch.
